name: ShopPlugin
version: '${version}'
main: de.joshua.ShopPlugin
api-version: '1.20'
authors: [ Joshua154 ]

commands:
  sell:
    description: sell Command
    permission: shopplugin.sell
  shop:
    description: shop Command
    permission: shopplugin.shop
  stored:
    description: stored Command
    permission: shopplugin.stored
  open:
    description: open specific Item Command
    permission: shopplugin.open
  announce:
    description: announce Item Command
    permission: shopplugin.announce
  offers:
    description: see offers Command
    permission: shopplugin.offers
  executeSQL:
    description: execute SQL Command
    permission: shopplugin.executeSQL