name: ShopPlugin
version: '${version}'
main: de.joshua.ShopPlugin
api-version: '1.20'
authors: [ Joshua154 ]

commands:
  shop:
    description: shop Command
    permission: shopplugin.shop
  open:
    description: open specific Item Command
    permission: shopplugin.open
  announce:
    description: announce Item Command
    permission: shopplugin.announce
  executeSQL:
    description: execute SQL Command
    permission: shopplugin.executeSQL